/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.draeger

import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import strikt.api.expectThat
import strikt.assertions.isNotNull

/**
 * A simple unit test for the 'tech.draeger.ok-bro' plugin.
 */
class OkBroPluginTest {
    @Test
    @Disabled
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("tech.draeger.ok-bro")

        // Verify the result
        expectThat(project.tasks.findByName("heyBro")).isNotNull()
    }
}
