/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.draeger

import org.junit.jupiter.api.Test
import strikt.api.expectThat
import strikt.assertions.contains

/**
 * A simple functional test for the 'tech.draeger.ok-bro' plugin.
 */
class OkBroPluginFunctionalTest {
    @Test
    fun `can run task`() {
        val result = createTestBuild(
            buildGradle = """
                plugins {
                    id('tech.draeger.ok-bro')
                }
            """
        ).runTask("heyBro")

        expectThat(result.output).contains("Hello from task")
    }

    @Test
    fun `dependencyUpdates task is available`() {

        val result = createTestBuild(
            buildGradle = """
                plugins {
                    id('tech.draeger.ok-bro')
                }
            """
        ).runTask("dependencyUpdates")

        expectThat(result.output).contains("Project Dependency Updates (report to plain text file)")

    }
}
