/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.draeger

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.Test
import strikt.api.expectThat
import strikt.assertions.contains

/**
 * A simple functional test for the 'tech.draeger.ok-bro' plugin.
 */
class OkBroPluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('tech.draeger.ok-bro')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()

        runner.withArguments("heyBro")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        expectThat(result.output).contains("Hello from task")
    }
}
